### PR TITLE
Adding name/description/license

### PR DESCRIPTION
**Pull request by GeoffreyDijkstra**
I have to revoke my statement about name and description not being part of a project.
It seems that packagist/composer are supporting the installation projects through composer.

What you need for this are tags on the project (which they don't have yet but I guess you can also use a branch like dev-master (not sure)). And in the composer file a name, description (optional?), type and license (optional?).

I found this information here and tested this with a symfony project.

Source:
https://getcomposer.org/doc/03-cli.md#create-project
https://getcomposer.org/doc/04-schema.md#type

Sorry for this, but at least I fixed it for you :grin:
We're all keep learning :smile:

### CODE REVIEW

**Comment by GeoffreyDijkstra** [comment]
What I forgot to mention is that your naming was incorrect. you used `"name": "Spotweb"` in `composer.json` while it had to be in this style: `"name": "%vendor%/%project"` so `"name": "spotweb/spotweb"`. Just a learning note :laughing:

**Comment by GeoffreyDijkstra** [comment]
Whoa fast response, thx for the merge. Let's hope the spotweb guys will add the composer pull-request.

**Comment by mbirth** [comment]
Yup. And then, the next step would be to use the fxp-asset plugin for Composer to also fetch those jQuery and other assets automatically. But I didn't yet check how much of those assets are in npm or bower.

**Comment by GeoffreyDijkstra** [comment]
I looked into what you said but it isn't possible to install it in a project according to this readme: https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md (If this is what you are referring to?)

**Comment by mbirth** [comment]
fxp is a (global) plugin for Composer so you have to install it using

    php composer.phar global require "fxp/composer-asset-plugin:~1.1"

But that's only one additional line in the (to be made) build/install script. Compared to having to install node.js, npm and bower. Or managing the external sources in the repository.

**Pull request merged**
